### ISSUE TITLE
Could not resolve host

### ISSUE THREAD

**Issue by lanyan520** [tzwm/sd-webui-model-downloader-cn#3]
0     0    0     0    0     0      0      0 --:--:--  0:00:29 --:--:--     0curl: (6) Could not resolve host: civitai-delivery-worker-prod-2023-06-01.5ac0637cfd0766c97916cefa3764fbdf.r2.cloudflarestorage.com

我开启vpn网站能自己下载，不开vpn镜像也能下载，安装这个插件能下载图片，模型每次下载都卡在这里，ping ip也平不出来

**Comment by tzwm** [comment]
这个 CDN 连接不上我没啥办法。
