### ISSUE TITLE
一个疑问

### ISSUE THREAD

**Issue by cslovewl** [tzwm/sd-webui-model-downloader-cn#5]
这个插件的作用和意义是什么呢？既然需要URL地址，那肯定是已经梯子到C站了，那在C站直接下载就行了啊。如果不能梯子到C站，也就不会知道模型URL地址，那这个插件也就没法用啊。所以是不是可以做成关键字搜索那样的，输入名称后，列出在C站上搜到的模型，提供预览给用户，然后可以选择下载。

**Comment by tzwm** [comment]
方便云端部署的 webui 使用。云端弄梯子稍微麻烦一点，特别是对小白用户。
